docs/challenges.md, services/web/public/index.html, services/web/src/components/navBar/navBar.js
Meta content change to reflect on sharing the url.
CRAPI -> crAPI
=> Meta content change

deploy/docker/docker-compose.yml, docs/challenges.md, services/identity/src/main/java/com/crapi/utils/MailBody.java, services/web/public/index.html, services/web/src/components/navBar/navBar.js, services/web/src/constants/messages.js, services/workshop/Dockerfile
-  #9 Update timeout in dockercompose.yml to 240
- Metadata and text
=> Metadata update

services/workshop/Dockerfile
Fixes #14: alpine version inconsistency
```
...
docker-compose-wait - Everything's fine, the application can now start!
--------------------------------------------------------
Operations to perform:
Apply all migrations: user
Running migrations:
Applying user.0001_initial... FAKED
Operations to perform:
Apply all migrations: crapi
Running migrations:
Applying crapi.0001_initial... OK
Operations to perform:
Apply all migrations: db
Running migrations:
Applying db.0001_initial... OK
django.utils.autoreload INFO     Watching for file changes with StatReloader
[22/Dec/2021 21:20:35] "GET /workshop/health_check/ HTTP/1.1" 200 888
```
=> Fixes #14: alpine version inconsistency

deploy/docker/docker-compose.yml, services/web/public/index.html
=> Build fixes

.github/workflows/docker-image.yml
build-docker-images on pull request
=> build-docker-images

.github/workflows/ci.yml
=> Fix tags syntax

.github/workflows/ci.yml
=> Fix workflow push condition

.github/workflows/ci.yml
=> Push condition workflow fix

.github/workflows/ci.yml
Correct indentation fixing workflow issues
=> Correct indentation fixing workflow issues

.github/workflows/ci.yml, deploy/docker/docker-compose.yml, services/community/build-image.bat, services/community/build-image.sh, services/identity/build-image.bat, services/identity/build-image.sh, services/mailhog/build-image.bat, services/mailhog/build-image.sh, services/web/build-image.bat, services/web/build-image.sh, services/workshop/build-image.bat, services/workshop/build-image.sh
Docker compose support variables for different release
=> Docker compose support variables for different release

.github/workflows/ci.yml
=> Update CI branch refs

.github/workflows/CONTRIBUTING.md, .github/workflows/ISSUE_TEMPLATE.md, .github/workflows/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, .github/workflows/code_of_conduct.md
This PR, 
- Adds contributing guidelines
- Adds Code of conduct
- Adds PR and Issue templates
- Configures path for running test workflows on PR.
=> chore: adds contributing guidelines, code of conduct, PR and issue templates

.github/workflows/ci.yml
Load built images in docker
Tested using local simulation of github actions
N/A
=> Load built images in docker

.github/workflows/ci.yml
Update latest tag on main merge
Update latest tag on main merge
Workflow
N/A
=> Update latest tag on main merge

.github/workflows/ci.yml
=> Release created -> published

README.md, docs/overview.md
=> Docs update 1

.github/workflows/ci.yml, docs/setup.md
=> Docs revision

services/community/build-image.sh, services/identity/build-image.sh, services/web/build-image.sh, services/workshop/build-image.sh
Build image script to exit on failure with message
Build script
=> Exit code and image name

services/workshop/crapi/mechanic/tests.py, services/workshop/crapi/merchant/tests.py, services/workshop/crapi/shop/tests.py, services/workshop/runner.sh, services/workshop/utils/jwt.py
Fixed all unit test cases. Running tests by default now.
Deployed and tested the service locally. 
=> Fixed errors in all unit test cases

docs/challengeSolutions.md
Refer to Issue https://github.com/OWASP/crAPI/issues/95
Created a template for challenge solutions page and provided detailed solutions for the below two challenges :  
Challenge 1 - Access details of another user’s vehicle
Challenge 2 - Access mechanic reports of other users
Challenge 8 - Get an item for free
Challenge 9 - Increase your balance by $1,000 or more
N.A.
Solutions are documented
=> Creation of challenge solutions page

services/web/src/components/navBar/nav.css, services/web/src/components/navBar/navBar.js
Refer to Issue #128 
`Some users feel that the User Profile can be improved. It is not clear to everyone that you can click on the profile photo to update account info.`
Have added a `pointer` style cursor to profile. In addition, nested the profile avatar inside a container that highlights to a color (`#1890ff`, as used in other button style elements in UI). 
Has been tested manually. 
N.A.
=> Improvements in user profile (Issue #128)

services/web/src/components/profile/profile.css, services/web/src/components/profile/profile.js
Made the Video Upload functionality prominent by putting it in a rectangular box. The button is visible on hovering over the dropdown.
Issue Link: https://github.com/OWASP/crAPI/issues/129
=> #129:Made Video Upload Functionality eminent

services/web/src/constants/constants.js
Regular Expression Validation for Password added
Password Validation Check #ISSUE 2  https://github.com/OWASP/crAPI/issues/2
=> Password Validation Check (ISSUE 2)

services/identity/src/main/java/com/crapi/config/InitialDataConfig.java, services/identity/src/main/java/com/crapi/exception/CRAPIExceptionHandler.java, services/identity/src/main/java/com/crapi/exception/EntityNotFoundException.java, services/identity/src/main/java/com/crapi/exception/IOExceptionHandler.java, services/web/src/constants/roleTypes.js
Add a default admin user : #119 
Reuse
=> Add admin user

.github/workflows/ci.yml, services/identity/src/main/java/com/crapi/config/JwtProvider.java, services/identity/src/main/java/com/crapi/entity/UserPrinciple.java, services/identity/src/main/java/com/crapi/enums/ERole.java
=> role in JWT

docs/challengeSolutions.md, docs/challenges.md, services/identity/src/main/java/com/crapi/config/JwtAuthTokenFilter.java, services/identity/src/main/java/com/crapi/config/JwtProvider.java, services/identity/src/main/java/com/crapi/config/WebSecurityConfig.java, services/identity/src/main/java/com/crapi/controller/AuthController.java, services/identity/src/main/java/com/crapi/service/Impl/UserServiceImpl.java, services/identity/src/main/java/com/crapi/service/UserService.java, services/identity/src/test/java/com/crapi/service/Impl/UserServiceImplTest.java
- Invalid Signature Vulnerability
- Algorithm Confusion Vulnerability
- JKU Misuse Vulnerability
- KID Path Traversal Vulnerability
- deployed and tested the service locally. 
- Ran postman collections
Documentation Updated
=> Implemented JWT Vulnerabilities

services/identity/src/main/java/com/crapi/config/InitialDataConfig.java, services/identity/src/main/java/com/crapi/constant/TestUsers.java, services/identity/src/main/java/com/crapi/controller/AuthController.java, services/identity/src/main/java/com/crapi/model/SeedUser.java, services/identity/src/main/java/com/crapi/service/Impl/UserServiceImpl.java, services/identity/src/main/java/com/crapi/service/UserService.java, services/identity/src/test/java/com/crapi/service/Impl/UserServiceImplTest.java
Added a reset endpoint to revert Test Users password to the default password.
Tested that the API is working as intended locally using docker images.
No documentation was made for this change.
=> Added A Reset Password for Test Users Endpoint to Identity Service

postman_collections/crAPI.postman_collection.json
Added new reset-test-users endpoint to postman collection
deployed and tested the service locally. 
=> Updated Postman Collection

postman_collections/crAPI.postman_collection.json, services/identity/src/main/java/com/crapi/controller/AuthController.java
GET should not change state. Use POST for reset
CI
=> Use POST for reset

services/workshop/crapi/mechanic/views.py
Auth mechanic report enforcement
CI
=> Auth mechanic report enforcement

services/community/api/router/routes.go
Fix Community Server open connections.
This fixes
Accept error: accept tcp [::]:8087: accept4: too many open files; retrying in 5ms
Automated
N/A
=> Fix Community Server open connections

services/community/api/controllers/post_controller.go, services/community/api/models/post.go
Add pagination support for posts
Tested on docker
=> Add pagination support for posts

.github/workflows/pr-build.yml, services/workshop/dev-requirements.txt
=> Fix pull workflow

services/identity/src/main/java/com/crapi/config/InitialDataConfig.java
Please include a summary of the change, motivation and context.
Audi RS7 and Mercedes-Benz run on petrol. Any owner of these cars who might be using this repo will most likely get triggered.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested the service locally. 
=> Fix fuel type for Audi and Mercedes-Benz

services/identity/src/main/java/com/crapi/model/VehicleLocationResponse.java, services/identity/src/main/java/com/crapi/service/Impl/VehicleServiceImpl.java, services/identity/src/test/java/com/crapi/service/Impl/VehicleServiceImplTest.java
=> ENG-0000: Fix vehicle location response

deploy/docker/docker-compose.yml, deploy/helm/templates/web/configmap.yaml, services/web/nginx-wrapper.sh, services/web/nginx.conf.template, services/web/nginx.ssl.conf.template
Add mailhog proxy for single lb support
Local
=> Add mailhog proxy for single lb support

services/identity/src/main/java/com/crapi/config/JwtAuthTokenFilter.java, services/identity/src/main/java/com/crapi/config/JwtProvider.java
Fix auth validation
Local
Make sure that you have documented corresponding changes in this repository. 
- [x ] I have added tests that prove my fix is effective or that my feature works
=> Fix auth validation

deploy/docker/docker-compose.yml, services/identity/src/main/java/com/crapi/config/JwtAuthTokenFilter.java, services/identity/src/main/java/com/crapi/config/JwtProvider.java
=> Release fixes to main

deploy/docker/docker-compose.yml, services/identity/src/main/java/com/crapi/config/JwtAuthTokenFilter.java, services/identity/src/main/java/com/crapi/config/JwtProvider.java
=> Revert "Release fixes to main"

services/identity/src/main/java/com/crapi/config/JwtAuthTokenFilter.java, services/identity/src/main/java/com/crapi/config/JwtProvider.java
=> Revert "Fix auth validation"
